# ==================== runtime ====================
seed: 42

# ONE dl block only
dl:
  device: cpu
  batch_size: 16
  num_workers: 0
  pin_memory: false
  persistent_workers: false
  optimizer: adamw
  lr: 1e-3
  weight_decay: 1e-4
  epochs: 20
  patience: 5
  grad_clip: 1.0
  model_dir: models

# ==================== paths =====================
paths:
  data_dir: raw_data
  artifacts_dir: experiments/artifacts
  checkpoints_dir: experiments/checkpoints
  # align with actual scaler output (your logs show features_scaled_ps)
  features_scaled_dir: features_scaled_ps

# ================== data files ==================
data_files:
  air: airquality.csv
  met: meteorology.csv
  station: station.csv
  district: district.csv
  city: city.csv
  forecast: weatherforecast.csv

# =========== canonical schema & headers =========
data:
  id_col: station_id
  station_col: station_id
  time_col: Datetime
  target: PM25_Concentration
  features:
    - CO_Concentration
    - NO2_Concentration
    - O3_Concentration
    - PM10_Concentration
    - SO2_Concentration
    - temperature
    - pressure
    - humidity
    - wind_speed
    - wind_direction
    - weather
    - up_temperature
    - bottom_temperature
    - wind_level
    - frequent
  headers:
    time: [Datetime, datetime, timestamp, time, date_time]
    id:   [station_id, "Station ID", StationId, stationID, site_id, station]
    airquality:
      station: ["Station ID", station_id, station, STATION_ID]
      time:    [Time, Datetime, time, timestamp, TIME]
      pm25:    [PM25_Concentration, "PM2.5", PM25, pm25, pm2_5, pm2.5, pm25_concentration]
      pm10:    [PM10_Concentration, PM10, pm10, pm10_concentration]
      no2:     [NO2_Concentration, NO2, no2, no2_concentration]
      co:      [CO_Concentration, CO, co, co_concentration]
      o3:      [O3_Concentration, O3, o3, o3_concentration]
      so2:     [SO2_Concentration, SO2, so2_concentration]
    station:
      station:  ["Station ID", station_id, station]
      district: ["District ID", district_id, district]
    district:
      district: ["District ID", district_id, district]
      city:     ["City ID", city_id, city]
    city:
      city:     ["City ID", city_id, city]
    meteorology:
      geo:            [ID, geo_id, id]
      time:           [Time, Datetime, time, timestamp]
      weather:        [Weather, weather]
      temperature:    [Temperature, Temp, AT, temperature, temp]
      pressure:       [Pressure, pressure, press]
      humidity:       [Humidity, RH, humidity, rh]
      wind_speed:     ["Wind Speed", WIND_SPEED, WindSpeed, wind_speed, ws]
      wind_direction: ["Wind Direction", WIND_DIREC, WindDirection, wind_direction, wd]
    weatherforecast:
      geo:                [ID, geo_id, id]
      ftime:              ["Forecast Time", ForecastTime, time_forecast, ftime]
      future:             ["Future Time", FutureTime, time_future, future_time]
      weather:            [Weather, weather]
      up_temperature:     ["Up temperature", UpTemperature, up_temperature, temp_high_c, temp_hi]
      bottom_temperature: ["Bottom Temperature", BottomTemperature, bottom_temperature, temp_low_c, temp_lo]
      wind_level:         ["Wind Level", WindLevel, wind_level]
      wind_direction:     ["Wind Direction", WIND_DIREC, wind_direction, WindDirection]

# ============ station selection (optional) ============
station_scope:
  mode: "all"
  station_ids: []

# ================= time split cutoffs =================
split:
  train_end: "2014-12-31"
  val_end:   "2015-03-31"

# ============== missing data handling ================
missing:
  drop_threshold: 0.8
  rolling_mean_hours: 24

# ==================== scaling ========================
scaling:
  type: standard

# ============== feature engineering ==================
lags:
  enabled: true
  hours: [1, 3, 6, 12, 24]

# =====================================================
# What the windowing + trainer actually read
# =====================================================
sequence:
  out_dir: seq
  train_split: train
  val_split: val
  test_split: test
  lookback: 168
  horizon: [1]
  stride: 12
  dropna: true
  shard_size: 15000
  dtype: float32
  check_max_shards: 2

baselines:
  seasonal_period: 168

model:
  hybrid:
    cnn_channels: [48, 48]
    cnn_kernels: [5, 3]
    cnn_dropout: 0.1
    d_model: 96
    nhead: 4
    num_layers: 2
    ff_mult: 2
    attn_dropout: 0.1
    ffn_dropout: 0.1
    head: seq2one
    pool: gap
    posenc: sin
    ln_eps: 1e-6

eval:
  metrics: ["rmse","mae","smape","r2"]
  per_station: true
  save_preds: true

sequence:
  out_dir: seq
  train_split: train
  val_split: val
  test_split: test
  lookback: 168
  horizon: [1]
  stride: 12
  dropna: true
  shard_size: 15000
  dtype: float32
  check_max_shards: 2
  dropna: false

